language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
  licenses:
    - '.+'

script:
  - ./gradlew test

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

sudo: false